# Generated by Django 4.1 on 2022-08-29 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineCompany',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_card_no', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('departure_time', models.TimeField()),
                ('landing_time', models.TimeField()),
                ('total_seats', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('rate', models.FloatField(default=0)),
                ('airline_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airline_company', to='base.airlinecompany')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_scheduled', to='base.day')),
                ('destination_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_country', to='base.country')),
                ('origin_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_country', to='base.country')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('total_rate', models.FloatField(default=0)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='base.customer')),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_tickets', to='base.flight')),
            ],
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.CheckConstraint(check=models.Q(('date__gt', django.db.models.functions.datetime.Now())), name='Day must be greated than today. Flights can only be scheduled and booked for upcoming days'),
        ),
        migrations.AddField(
            model_name='customer',
            name='airlines_managed',
            field=models.ManyToManyField(to='base.airlinecompany'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
